source:
  driver: pgx
  url: postgres://postgres:password@localhost:5432/store?sslmode=disable
  tables:
    - name: product
      read_limit: 1000
      filter: WHERE created_at < '2023-08-03 12:25:40.689503'
      columns:
        - name: id
        - name: name
        - name: created_at

target:
  url: postgres://root@localhost:26257/store?sslmode=disable
  tables:
    - name: product
      columns:
        - name: id
        - name: name
        - name: created_at