source:
  driver: pgx
  url: postgres://postgres:password@localhost:5432/postgres?sslmode=disable
  tables:
    - name: person
      primary_key: id
      read_delay: 2s
      read_limit: 2
      columns:
        - name: id
        - name: full_name
        - name: date_of_birth

target:
  url: postgres://root@localhost:26257/defaultdb?sslmode=disable
  tables:
    - name: person
      primary_key: id
      columns:
        - name: id
        - name: full_name
        - name: date_of_birth